jwt:
  # 签发人
  issuer: zmx
  # 秘钥
  secret: YxF4Es8DzGXcIrFQqZGzg3EkV1CasbxToLxariE4Fm0G8smKjsuAuj4l3d7DBR4zGCk/9YBZuW2nL0qxYFfbfw==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer
